name: Build and deploy Android app to Firebase

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1.5.1
        with:
          flutter-version: '3.7.12' # specify the version of Flutter you want to install
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
      - name: Decode firebase_option
        env:
          firebase_options_dart: ${{secrets.FIREBASE_OPTIONS}}
        run: echo "$firebase_options_dart" > lib/firebase_options.dart
      - name: Install dependencies
        run: flutter pub get
      - name: Build Android app
        run: flutter build apk
        if: ${{ github.ref == 'refs/heads/main' }}
      - name: Upload Android app to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APPID }}
          token: ${{ secrets.TOKEN }}
          groups: idea-usher
          file: build/app/outputs/apk/release/app-release.apk
        if: ${{ github.ref == 'refs/heads/main' }}
